version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: medical_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: medical_db
    ports:
      - "5455:5432"
    volumes:
      - postgres_data_5455:/var/lib/postgresql/data

volumes:
  postgres_data_5455: