version: '3.8'

services:
  app:
    container_name: medical_api_app
    build: .
    ports:
      - "8080:8080" # Recuerda el ajuste del puerto que hicimos antes
    environment:
      # VARIABLES DE BASE DE DATOS
      DB_URL: jdbc:postgresql://postgres-db:5432/medical_db
      DB_USERNAME: admin
      DB_PASSWORD: adminpassword_super_seguro
      
      # VARIABLE JWT (Â¡AquÃ­ va la clave real!)
      # Nota: Debe ser larga (min 32 caracteres) para HS256
      JWT_SECRET_KEY: esta_es_una_clave_secreta_muy_larga_y_segura_para_produccion_2026
      
    depends_on:
      - postgres-db
    restart: always

  postgres-db:
    image: postgres:15-alpine
    container_name: medical_db
    environment:
      POSTGRES_USER: admin
      # Tiene que coincidir con la de arriba ðŸ‘†
      POSTGRES_PASSWORD: adminpassword_super_seguro 
      POSTGRES_DB: medical_db
    ports:
      - "5455:5432"
    volumes:
      - postgres_data_5455:/var/lib/postgresql/data

volumes:
  postgres_data_5455: